on: [workflow_dispatch]

jobs:
  run_container:
    runs-on: ubuntu-latest
    name: Run container
    container:
      image: ogoldobina/point_grid:v1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download data
      run: |
        chmod +x ./download.sh
        ./download.sh
    - name: Prepare data
      run: python ./prepare.py
    - name: Train model
      run: python ./code/train.py
    - name: Test model
      run: python ./code/test.py
